#!/bin/bash

# Setup script to configure Docker environment with correct user permissions

echo "Setting up Docker environment for MT4 converter..."

# Get current user's UID and GID
CURRENT_UID=$(id -u)
CURRENT_GID=$(id -g)
CURRENT_USER=$(whoami)

echo "Current user: $CURRENT_USER (UID: $CURRENT_UID, GID: $CURRENT_GID)"

# Create .env file if it doesn't exist
if [ ! -f .env ]; then
    echo "Creating .env file with current user settings..."
    cat > .env << EOF
# Environment variables for Docker build and runtime
# Auto-generated by setup-docker-env.sh

# User and group IDs for the container user
USER_ID=$CURRENT_UID
GROUP_ID=$CURRENT_GID

# Container username (using current username)
CONTAINER_USER=$CURRENT_USER

# VNC settings
VNC_PASSWORD=mt4vnc
VNC_RESOLUTION=1280x720
VNC_DEPTH=24

# Python settings
PYTHONUNBUFFERED=1

# Wine settings
WINEDEBUG=-all

# Timezone
TZ=UTC
EOF
    echo ".env file created successfully!"
else
    echo ".env file already exists. Updating user settings..."
    # Update existing .env file with current user settings
    sed -i "s/^USER_ID=.*/USER_ID=$CURRENT_UID/" .env
    sed -i "s/^GROUP_ID=.*/GROUP_ID=$CURRENT_GID/" .env
    sed -i "s/^CONTAINER_USER=.*/CONTAINER_USER=$CURRENT_USER/" .env
    echo ".env file updated!"
fi

echo ""
echo "Environment setup complete!"
echo ""
echo "You can now run the Docker container with:"
echo "  docker-compose -f docker-compose.safe.yml up --build"
echo ""
echo "Or rebuild the image:"
echo "  docker-compose -f docker-compose.safe.yml build --no-cache"
echo ""
echo "The container will run with your user permissions (UID: $CURRENT_UID, GID: $CURRENT_GID)"